# docker-compose version
version: '3.6'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    network_mode: 'host'
    ports:
      - 8080:8080
