# docker-compose version
version: "3.6"

volumes:
  postgres-volume:
  redis-volume:

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    restart: always
    volumes:
      - ./apps/api:/app/apps/api
      # - ./packages:/app/apps/packages
      # - /app/apps/api/node_modules
    ports:
      - 5000:5000
    networks:
      - app_network

  # nginx:
  #   restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - server
  #     - client

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true