const typeDefs = `#graphql
  # Comments in GraphQL strings (such as this one) start with the hash (#) symbol.

  ####################################### Interfaces #######################################
 
  ####################################### Enums #######################################
  enum UserStatus {
    ONLINE
    OFFLINE
    WORKING
  }
  
  enum UserRole {
    ADMIN
    USER
  }

  enum CaptchaStatus {
    CREATED
    RESOLVING
    RESOLVED
  }


  ####################################### Types #######################################
  type User {
    id: String!
    username: String!
    role: UserRole!
    status: UserStatus!
  }

  type Captcha {
    id: ID! # Database ID
    captchaId: ID! # ID Generated By Gotcha App
    name: String!
    status: CaptchaStatus!
    text: String!
    createdAt: String!
    updatedAt: String!
  }

  ####################################### Inputs #######################################
  input CreateCaptchaInput {
    captchaId: ID!
    name: String!
  }

  input ResolveCaptchaInput {
    captchaId: ID!
    text: String!
  }

  input LoginInput {
    username: String!
    password: String!
  }

  input OnUserUpdatedInput {
    userId: ID!
  }

  input OnUpsertCaptchaInput {
    captchaId: ID!
  }

  ####################################### Query #######################################
  type Query {
    me: User!
    users: [User!]!
    captchas: [Captcha!]!
    captcha(captchaId: ID!): Captcha
    assignedCaptcha: Captcha
  }

  ####################################### Mutation #######################################
  type Mutation {
    login(input: LoginInput!): User!
    logout: Boolean!
    createCaptcha(input: CreateCaptchaInput!): Captcha!
    resolveCaptcha(input: ResolveCaptchaInput!): Captcha!
  }

  ####################################### Subscription #######################################
  type Subscription {
    onUserUpdated(input: OnUserUpdatedInput!): User!
    onUpsertCaptcha(input: OnUpsertCaptchaInput): Captcha!
    onCreateCaptcha: Captcha!
    captchaAssigned(userId: ID!): Captcha!
    hello: String!
  }
`;

export default typeDefs;
